services:
  backend:
    container_name: backend
    build:
      context: ../Server
      dockerfile: ../Server/Moneys/Dockerfile
    ports:
      - "8080:8080" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:PostgresConnection=Host=postgres;Database=moneys;Username=localuser;Password=password
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moneys
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
